name: Build and Publish Package

on: 
    push:
        branches: [ "main"]
    pull_request:
        branches: [ "main" ]
    release:
        types: [published]
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 25
      - run: npm ci
      - run: npm run build 
      - run: npm run coverage
      # TODO: - run: npm test
  publish_package:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        repository-projects: write
        packages: write
        id-token: write 
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js pre npmjs.com
        uses: actions/setup-node@v4
        with:
          node-version: '25' 
          registry-url: 'https://registry.npmjs.org/'
          
      - run: npm ci
      - run: npm run build      
      
      - id: semver
        uses: ildug/get-tag-action@v1
        
      - run: npm version --git-tag-version=false ${{ steps.semver.outputs.version }} 
      
      - name: Publish to NPM
        run: npm publish --provenance --access public

      - name: Prekonfigurovanie na GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '25'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@polyfea'

      - name: Publish to GitHub Registry
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload boot-mjs
        uses: WebFreak001/upload-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./dist/sw.mjs
          mime: application/javascript
          name: sw.mjs

      - name: upload boot-mjs
        uses: WebFreak001/upload-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./dist/register.mjs
          mime: application/javascript
          name: register.mjs
      
      
      
      